### ISSUE TITLE
Login username

### ISSUE THREAD

**Issue by gregvp00** [vincentmathis/osu-beatmap-downloader#1]
I have an username separated by spaces "My Bpm Sucks" and I can't login

**Comment by vincentmathis** [comment]
Can you check if [https://osu.ppy.sh/](https://osu.ppy.sh/) is online for you?

I can't login myself right now because the osu website gives Error 429: Too Many Requests

**Comment by gregvp00** [comment]
> Can you check if https://osu.ppy.sh/ is online for you?
> 
> I can't login myself right now because the osu website gives Error 429: Too Many Requests

Yes, I have checked my login credentials and that's not the problem

**Comment by vincentmathis** [comment]
See issue #3, the website added a token to the login form and I currently don't know how to integrate this
