### ISSUE TITLE
I would like to know how you know which parameters to use when searching

### ISSUE THREAD

**Issue by boogieLing** [vincentmathis/osu-beatmap-downloader#10]
In  Downloader.scrape_beatmapsets, you implemented a shift in search results by using "favourite_count" field. 
So I want to know where you know that. And, are there more fields available?

MANY THANKS!!!

**Comment by vincentmathis** [comment]
I opened my browsers developer tools on https://osu.ppy.sh/beatmapsets and checked the URL parameters. You can choose different sorting method and will see different type of parameters. You can sort by

- Title
- Artist
- Difficulty
- Ranked
- Rating
- Plays
- Favourites

```json
{
	"beatmapsets": [],
	"search": {
		"sort": "plays_desc"
	},
	"recommended_difficulty": 4.649137125571559,
	"error": null,
	"total": 34198,
	"cursor": {
		"play_count": "26505314",
		"id": "201141"
	},
	"cursor_string": "eyJwbGF5X2NvdW50IjoiMjY1MDUzMTQiLCJpZCI6IjIwMTE0MSJ9"
}
```

The results are paginated via the `cursor` parameter which rests on the last beatmap in the `beatmapsets` list.
