### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by jt-z** [vincentmathis/osu-beatmap-downloader#2]
It doesn't work.I don't know what I did wrong although I step by step according to the README file.

**Comment by vincentmathis** [comment]
See issue #3, the website added a token to the login form and I currently don't know how to integrate this

**Comment by jt-z** [comment]
Thanks for you reply! I'm going to the issue [#3](https://github.com/vincentmathis/osu-beatmap-downloader/issues/3)
