### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by thecatontheceiling** [vincentmathis/osu-beatmap-downloader#3]
I can't use the downloader because it says Login Failed! , I am sure that I entered my correct password and username

**Comment by roansong** [comment]
I have encountered the same issue when trying to post to https://osu.ppy.sh/session with "username" and "password" set. It looks to me like they added a csrf token on the login form, which might be the issue.
There's a "_token" field in the submitted form data when I check my network panel and log in on the site.

**Comment by vincentmathis** [comment]
> There's a "_token" field in the submitted form data when I check my network panel and log in on the site.

You're right. Any idea on where I get that token from programmatically? The token is different every time.

**Comment by roansong** [comment]
@vincentmathis I've got a basic workaround - you need to call the osu! homepage, find the CSRF token (I used a simple regex but you could use BeautifulSoup to parse the HTML and look for it too) and then use this token in your POST request to `/session`.

```
import requests
import re

OSU_URL = "https://osu.ppy.sh/home"
OSU_SESSION_URL = "https://osu.ppy.sh/session"

session = requests.Session()

# access the osu! homepage
homepage = session.get(OSU_URL)

# extract the CSRF token sitting in one of the <meta> tags
regex = re.compile(r".*?csrf-token.*?content=\"(.*?)\">", re.DOTALL)
match = regex.match(homepage.text)
csrf_token = match.group(1)

data = {
    "_token": csrf_token,
    "username": "username",
    "password": "password",
}

# This header needs to be set
headers = {"referer": OSU_URL}

res = session.post(OSU_SESSION_URL, data=data, headers=headers)
if res.status_code != requests.codes.ok:
    print("login failed")
else:
    print("logged in successfully")

```

**Comment by vincentmathis** [comment]
Should work now

**Comment by vincentmathis** [comment]
The downloads were failing, I think I had to add a referer url to the download GET requests too.

I published a new version that works for me, let me know if you still encounter issues.

**Comment by ghost** [comment]
Should reopen this. Login isn't working again, and too many attempts results in "429 Too Many Requests"

**Comment by vincentmathis** [comment]
> Should reopen this. Login isn't working again, and too many attempts results in "429 Too Many Requests"

Are you sure? I just ran the app without problems. Do you have to most recent version installed?

**Comment by ghost** [comment]
![2021-09-23_16-38](https://user-images.githubusercontent.com/34766434/134477914-f6a5962b-1514-434a-82b2-3247ddb357ca.png)
On first run it would run fine for about 2000+ beatmaps. Then the download will stop (probably because I downloaded too much). After that I just get this screenshot everytime, ocassionally it would work for a while.

**Comment by vincentmathis** [comment]
Okay so the login works and this is probably because the osu website limits your requests after downloading too much.
I should add better errorhandling for this so the user knows what is happening.

Sadly i don't think there is any way around this besides just waiting until the website lets you download again.

**Comment by ghost** [comment]
I thought it could be down time from the server. But does 4~5 days sound like the normal range for downtime? That's what I've been getting and why I thought it only ocassionally works.

**Comment by vincentmathis** [comment]
Okay so I tried reproducing the error and this is how it looks when the website limits your access. This resolves after about 30 minutes or an hour.

```
2021-09-23 11:04:04 | SUCCESS  | File write successful
2021-09-23 11:04:06 | INFO     | Downloading beatmapset: 801074 DatManOvaDer - Busta Rhymes Goes To The Wii Shop Channel
2021-09-23 11:04:07 | WARNING  | 429 - Download failed
2021-09-23 11:04:07 | INFO     | Downloading beatmapset: 801074 DatManOvaDer - Busta Rhymes Goes To The Wii Shop Channel
2021-09-23 11:04:07 | WARNING  | 429 - Download failed
2021-09-23 11:04:07 | INFO     | Downloading beatmapset: 801074 DatManOvaDer - Busta Rhymes Goes To The Wii Shop Channel
2021-09-23 11:04:07 | WARNING  | 429 - Download failed
2021-09-23 11:04:07 | INFO     | Downloading beatmapset: 1174505 The Cab - Angel With A Shotgun (Sped Up Ver.)
2021-09-23 11:04:08 | WARNING  | 429 - Download failed
2021-09-23 11:04:08 | INFO     | Downloading beatmapset: 801074 DatManOvaDer - Busta Rhymes Goes To The Wii Shop Channel
2021-09-23 11:04:08 | WARNING  | 429 - Download failed
2021-09-23 11:04:08 | ERROR    | Failed 5 times in a row
2021-09-23 11:04:08 | INFO     | Website download limit reached
2021-09-23 11:04:08 | INFO     | Try again later
2021-09-23 11:04:08 | INFO     | ############# DOWNLOADER TERMINATED ##############
```

Are you still experiencing the JSONDecodeError right now?

**Comment by ghost** [comment]
Yes. I've tried deleting credentials but still the same. I'm on arch running python 3.9.6. Also I have osu! supporter if thats relevant.

**Comment by vincentmathis** [comment]
Could you clone this repo and add a breakpoint to the `response` variable in line 148 in downloader.py? Or add a try/catch block around line 149 and log out to console.

You need [poetry](https://python-poetry.org/) to install the dependencies into a virtual environment.

**Comment by ghost** [comment]
I will do that asap, probably tomorrow (12hrs-ish due to timezone)

**Comment by vincentmathis** [comment]
Thank you, but there is no need for hurry :)

**Comment by ghost** [comment]
Sorry for a very late reply. I have sinced then traveled to a different country with different internet connection and computer. I was unable to reproduce the problem. I will update again if I'm back home to troubleshoot it.
