### ISSUE TITLE
Add support for download without video

### ISSUE THREAD

**Issue by ghost** [vincentmathis/osu-beatmap-downloader#6]
There a flag "?noVideo=1" that can be used to download without video. I've currently edited line 170 in downloader.py from "/download" to "/download?noVideo=1". Not sure whether this will support downloading beatmaps without videos already.

Would you consider adding an option --no-video / -n to support that?

**Comment by vincentmathis** [comment]
I added the option to add `?noVideo=1` via the `--no-video | -nv flag`. I haven't checked if the downloaded files really are missing the video or not.

If you want to try it, you have to install the new version via pip.

**Comment by ghost** [comment]
Thanks! I'll try it out

**Comment by ghost** [comment]
Hello, I've just download a new batch of 100 beatmaps with the latest version, and I've checked several of them with the osu website too to make sure there was a video version and that the downloaded beatmap has no videos.

Consider this done! Thank you for your work.
